### ISSUE TITLE
Optimus service won't start without "AllowEmptyInitialConfiguration" "True"

### ISSUE THREAD

**Issue by ghost** [pouya-eghbali/freebsd-nvidia-optimus#1]
Hi,

   First of all, thank you so much for putting this package together! I can finally use Optimus on my laptop in FreeBSD without having to use Linux. :+1: 

   I couldn't get the optimus service to run unless I modified the the display device section to the following:
```Section "Device"
    Identifier "Device1"
    Driver "nvidia"
    VendorName "NVIDIA Corporation"
    BusID "1:0:0"
    Option "NoLogo" "true"
    Option "UseEDID" "false"
    Option "ConnectedMonitor" "DFP"
    Option "AllowEmptyInitialConfiguration" "True"
EndSection
```
Without the "AllowEmptyInitialConfiguration" "True" I was getting the `(EE): No screens found` error.

Thanks,
Tom

**Comment by shak3800** [comment]
Hi there

Is this your own xorg or the one that optimus drivers install ?

**Comment by ghost** [comment]
@shak3800 This is the xorg config file that the optimus drivers install.

**Comment by shak3800** [comment]
@tdm4 Thanks for the reply. In your case does the service start on boot? Also are you using also an xorg.conf file or configuration files in the x11 directory? Could you share it?

**Comment by ghost** [comment]
@shak3800 no, my service doesn't start on boot.. I have to start it after I've logged in with `startx` (I don't use xdm or slim).

I just use the xorg.conf file the package provides and added that one line as documented above.

**Comment by shak3800** [comment]
@tdm4 Thanks a lot.

In my case the service cant start on boot. If i start it manually the fans start to load . cpu usage also goes up i can hear the laptop stressing. One thing i notice is that even though optimus is not enabled nvidia still runs. You can tell bt checking the gpu temp. Just intel is used by default but nvidia still runs. So laptop is hotter and consumes more power.

Can you confirm?

**Comment by pouya-eghbali** [comment]
WOW, sorry I didn't see any of these issues posted I don't know why but I didn't receive any notifications about them (I was too busy with other work I guess) I'll start working on these issues today. Sorry @everyone.

**Comment by pouya-eghbali** [comment]
@tdm4 I merged your pull request, @shak3800 I'll investigate the CPU issue, there are ways to turn off the nvidia gpu, I'll add that to the port, however that doesn't work for everyone (it causes more issues for me for example) so I'll make it optional and configurable in the rc files.

**Comment by shak3800** [comment]
@pouya-eghbali i think in my case the service doesnt manage to start manually. The window with the xorg output just stays there and the cpu usage increases.

**Comment by pouya-eghbali** [comment]
@shak3800 can you try this? Do not enable the service, just install the port. Then do the following:

1. Get bus id using this command:

```
pciconf -lv | grep NVIDIA -B1
```

It'll output something like:

```
vgapci0@pci0:1:0:0:     class=0x030200 card=0x22ca1043 chip=0x139110de rev=0xa2 hdr=0x00
    vendor     = 'NVIDIA Corporation'
```

where 1:0:0 is the bus id of the nvidia gpu.

2. Create a Xorg config file in `/usr/local/etc/X11/` for example `optimus.conf`, then put this configuration in it:

```
Section "ServerLayout"
    Identifier "Layout0"
    Option "AutoAddDevices" "false"
    InputDevice "fake" "CorePointer"
EndSection

Section "Device"
    Identifier "Device1"
    Driver "nvidia"
    VendorName "NVIDIA Corporation"
    BusID "1:0:0"
    Option "NoLogo" "true"
    Option "UseEDID" "false"
    Option "ConnectedMonitor" "DFP"
    Option "AllowEmptyInitialConfiguration" "True"
EndSection

Section "InputDevice"
    Identifier "fake"
    Driver ""
EndSection

Section "Files"
    ModulePath "/usr/local/lib/xorg/modules/extensions/.nvidia-optimus/"
    ModulePath "/usr/local/lib/xorg/modules"
EndSection
```
Change the bus id to the one you got in step 1.

3. Start your primary X server using the intel driver. This is needed because Nvidia gpu doesn't have direct write access to the display and instead it writes to intel gpu buffer. After starting the X server on intel gpu, use the config file you created above to start a new X server for Nvidia:

```
X -config "optimus.conf" -sharevts -noreset :8
```

4. Now you can call vglrun to run programs on the Nvidia gpu, I suggest running glxinfo to see if it works:

```
/usr/local/VirtualGL/bin/vglrun -ld /usr/local/lib/nvidia -d ":8" glxinfo | grep renderer
```

Let me know how this goes and in which step the cpu usage goes up. Don't forget to `kldload nvidia` and/or `kldload nvidia-modeset` before doing the above.

**Comment by ghost** [comment]
Hey thanks @pouya-eghbali !
Yeah I noticed if I start X using the optimus.conf like above on :8 immediately one of my CPU's goes to 100% and the fan starts to go crazy on my laptop as well. It stays like that until I'm done with the app I run with vglrun, and then if I stop the optimus service.. only then does the fan stop going crazy.

I noticed glxinfo does segfault too. I didn't dump core on it so not sure what is causing that.

**Comment by ghost** [comment]
Going to close this issue as the PR's been merged in. Thanks! :+1:
