### ISSUE TITLE
Not an issue rather a question

### ISSUE THREAD

**Issue by shak3800** [pouya-eghbali/freebsd-nvidia-optimus#2]
Should the xorg conf file have both intel and nvidia devices? What happens when a new driver get released? I dont suppose nvidia-xrun works with freebsd? Lastly does optirun work with wine and steam?

Thanks a lot for your time and effort

**Comment by pouya-eghbali** [comment]
I do not know how to achieve that. When a new driver gets released, if there are no major / breaking changes we need to modify the version number in build file (there were breaking changes between 390 and 430 so I had to do a lot more than just modifying the version).

For the first question, https://wiki.archlinux.org/index.php/Nvidia-xrun says:

> X server can only be used with integrated graphics or discrete Nvidia graphics, **but not both**, so user might want to switch to separate virtual console and start another X server using different graphics from what was used for the first X server.

I've never used nvidia-xrun and don't know how it works or what it is... `optirun` uses `vglrun` to run programs on the nvidia gpu, latest virtualgl version on ports is 2.4.1,

https://cdn.rawgit.com/VirtualGL/virtualgl/2.4.1/doc/index.html does not mention wine compatibility, however 2.1.1 does mention wine. Bumblebee also uses virtualgl afaik so if runs on bumblebee it should run with this port too.
